on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v4
      - run: docker buildx build --platform linux/amd64,linux/arm64/v8 .
        # TODO: automatically release
